### ISSUE TITLE
IC: limitations and Expectations

### ISSUE THREAD

**Issue by ChanceFleeting** [ChanceFleeting/Fleeting_BMEDesign#2]
Is there a limit on what ICs we can use? If we were expected to use a single button, I was going to connect it to a ring counter to iterate through states (I’m working relatively hard to avoid using a microprocessor for this application) in conjunction to limited control logic, but such a system would be relatively laborious to manually build out of discrete transistors. Using specific ICs for such a task would be pretty helpful. 

That also being said, would we (realistically) have an opportunity to use, apply, and print some sort of HDL-synthesis technique to print our own integrated circuit with embedded transistors for this type? It would be really cool to focus this circuit down to the minimum basics that I would need.

**Comment by mlp6** [comment]
The IC is not specified in any way, so you have a wide-open playing field for that.  There is the imposed constraint of using a single button though.  Avoiding the use of an MCU is a good starting point; that would be an 800 lb gorilla for this problem, though it is a viable solution.
