### ISSUE TITLE
Analog Schematic Review

### ISSUE THREAD

**Issue by ChanceFleeting** [ChanceFleeting/Fleeting_BMEDesign#3]
I put together a schematic for the analog option for my flash light (with sub systems labelled). Would you be able to review it to see if anything is strikingly incorrect? 

I think I was able mitigate the chaos between the LFO and HFO, but well see. 

Thank you.

**Comment by ChanceFleeting** [comment]
https://github.com/ChanceFleeting/Fleeting_BMEDesign/blob/master/Semester1Design/Electronics/FlashingLightScheme1Disc.pdf

**Comment by mlp6** [comment]
On quick inspection the functional stages look good, but this is one that I would mock up before committing on a PCB.  I have some concern about the timing between the stages and getting caught in a locked up or unstable state if timing is not guaranteed.
