### ISSUE TITLE
Milestone 4: ECAD Itteration 1

### ISSUE THREAD

**Issue by ChanceFleeting** [ChanceFleeting/Fleeting_BMEDesign#5]
I'm sorry this is late. It has been a crazy week.
My current Itteration of the base design:
https://github.com/ChanceFleeting/Fleeting_BMEDesign/tree/master/Semester1Design/Electronics/PCB

**Comment by ChanceFleeting** [comment]
I will @sphearobolus as soon as my collaboration request is returned

**Comment by mlp6** [comment]
Looking good!  @sphaerobolus for final confirmation

**Comment by sphaerobolus** [comment]
board looks good to me*. In the schematic, I'd replace the misleading BJT symbol with one that better represents your voltage regulator. 

*Just make sure the voltage regulator in the TO-92 case can supply the current you need. I'm pretty sure it can, but make certain.

**Comment by ChanceFleeting** [comment]
@sphaerobolus, for the TO-92 package of the 7805, is the model that we are working with the same thing as LM78L05? If so, the Io seems to be 40mA (I attached a source below p2) , which should be good according to what I observed on Monday. Also, I definitely agree with the fact I should replace the BJT symbol. I left it in there so that I would have the right footprint for the TO92 case. I will fix that in this iteration.

Thank you!

LM78L05: http://users.ece.utexas.edu/~valvano/Datasheets/LM78L05.pdf

**Comment by sphaerobolus** [comment]
the 78L05 is, indeed, what we have.

**Comment by ChanceFleeting** [comment]
Thank you!
I have fixed and adjusted the Schematic and PCB:
> put the LM78L05 into the model
> replaced the NPN BJT with a 2N7000 NMOS
> replaced the Capacitor values
> changed the PCB form

I'm also looking at bumping my trace widths. Right now I have 20 mil for the power line and 10 mil for the signal lines.

Linked: https://github.com/ChanceFleeting/Fleeting_BMEDesign/blob/master/Semester1Design/Electronics/PCB/ECAD%20files/PCB_Project1.pdf

**Comment by ChanceFleeting** [comment]
@mlp6 and @sphaerobolus  Is there any  adjustments I need to make on my PCB before it is ready to print?

Linked: https://github.com/ChanceFleeting/Fleeting_BMEDesign/blob/master/Semester1Design/Electronics/PCB/ECAD%20files/PCB_Project1.pdf

**Comment by sphaerobolus** [comment]
looks good!
